### ISSUE TITLE
[1.17.1][FABRIC][COMPATIABILITY] - William Wythers' Overhauled Overworld

### ISSUE THREAD

**Issue by HalestormXV** [DimensionalDevelopment/DimDoors#232]
Not sure if this is an issue or just unlucky. I cannot seem to find any Dimensional Doors when using William Wythers; Overhauled Overworld. I am well aware that his mod says it may not be compatible with structure and ore gen mods but does Dimensional Doors fall into that category? On second note I am setting the WorldType to Large Biome, but on Default I also didn;t seem to find anything. So again, not sure if it is just unlucky or an actual incompatibility.

**Comment by BoogieMonster1O1** [comment]
This is an issue on our side, I'll push a fix soon

**Comment by BoogieMonster1O1** [comment]
Should be fixed in 8cffb582
Gateways should now generate in any kind of modded biomes now
![2021-09-27_10 59 53](https://user-images.githubusercontent.com/62552372/134850463-601165dd-a6c0-43a5-891a-0b24d130c760.png)
![2021-09-27_11 01 19](https://user-images.githubusercontent.com/62552372/134850470-35c3d468-619b-4535-b10e-d5aca8f9c82c.png)
I'll publish to curseforge later today
