### ISSUE TITLE
Can't get out of limbo

### ISSUE THREAD

**Issue by HacoKavanah** [DimensionalDevelopment/DimDoors#271]
In the newest two updates the reality liquid has stopped working! It just does nothing!

**Comment by Waterpicker** [comment]
I know what happened. I was being messy and didn't properly push my attempts at making a proper fix for https://github.com/DimensionalDevelopment/DimDoors/issues/265 to a proper branch or stash it.

The half done fix attempt broke Eternal fluid because it uses the same backend as the oak dimensional doors got borked. It got mixed in when I was hastily throwing together the uwulith prank together for april fools.
