### ISSUE TITLE
Personal Pocket dimension clearing

### ISSUE THREAD

**Issue by JoshManTheGuy** [DimensionalDevelopment/DimDoors#294]
I have seen issues where a new pocket dimension is generated far away from the original one and the original still exists.

I do not believe this to be the case as I am playing on a modpack with journeymap and the coordinates are the same suggesting that the new pocket dimension is overwriting the old one.

**Comment by DoctorMage** [comment]
Having the same issue tested with just dim doors
DimensionalDoors-1.12.2-3.0.11.jar and contents wiped 
https://youtu.be/NvI1ChzcUKE

Logs 
[debug.log](https://github.com/DimensionalDevelopment/DimDoors/files/9070156/debug.log)
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/9070157/latest.log)

Testing with waystone and journeymap
journeymap-1.12.2-5.7.1.jar
Waystones_1.12.2-4.1.0.jar

After some testing with waystones
I'm guessing the issue is related to the player entering from the door as leaving has no issues
orginally noticed in  a larger modpack but another thing was a chunk loading block was able to save it partially but still got reset after leaving and renentering enough times

[debug.log](https://github.com/DimensionalDevelopment/DimDoors/files/9070210/debug.log)
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/9070211/latest.log)

https://youtu.be/AW-gYwdn5dg
