### ISSUE TITLE
Foamfix incompatibility

### ISSUE THREAD

**Issue by Runemoro** [DimensionalDevelopment/DimDoors#36]
https://paste.ee/p/gN2fE

**Comment by Robijnvogel** [comment]
Nullpointer on this line:
https://github.com/DimensionalDevelopment/DimDoors/blob/1.12-WIP/src/main/java/org/dimdev/dimdoors/shared/tools/SchematicConverter.java#L120
Caused by [this method call](https://github.com/DimensionalDevelopment/DimDoors/blob/1.12-WIP/src/main/java/org/dimdev/dimdoors/shared/tools/SchematicConverter.java#L256) returning null:
`TileEntity.getKey(TileEntityHopper.class)`

But only when Foamfix is installed.

**Comment by Runemoro** [comment]
Yeah, FoamFix replaces the TileEntityHopper with TileEntityFasterHopper. A workaround would be hardcoding the IDs.
