### ISSUE TITLE
Not an issue really, but is there a changelog anywhere?

### ISSUE THREAD

**Issue by noicknoick** [DimensionalDevelopment/DimDoors#38]

**Comment by lag42** [comment]
There's the commits log on here and then there's the beta changelogs on curseforge

**Comment by Robijnvogel** [comment]
@noicknoick are you looking for a list of things that are different between this mod, the 1.6.4 version and the 1.7.10 port? Because I don't think we have enough time to actually write that list at the moment.

The most prominent change is that not each pocket is placed in a new dimension, which should be way better for server performance.
Both on the CurseForge Page and the Minecraft Forums thread, you can see that we have a public Discord server where you're more than welcome to hang out and ask us casual questions. :)

Closing this issue as it's not an issue.
