### ISSUE TITLE
Crash on World Generation

### ISSUE THREAD

**Issue by ScytheIronclaw** [DimensionalDevelopment/DimDoors#42]
Mod version 3.0.6-b227
Forge version 14.23.1.2601
also encountered the same issue with 3.0.6-b228

When generating a new world the game crashes at the dirt screen.
Logs mention about an invalid block ID in an existing schematic.

[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/1670537/latest.log)

**Comment by Robijnvogel** [comment]
@ScytheIronclaw 
_FYI, we prefer you use pastebin.com or gist over linking to an uploaded file._ :)
Also, it would be nice to have the crash report or the `fml-server-latest.log` instead of the `latest.log`. In 99% of all cases, those are the ones that'd contain the useful information.

"This crash report has been saved to: `C:\Users\<your user-name>\Documents\Curse\Minecraft\Instances\Custom 1.12\crash-reports\crash-2018-01-27_16.05.22-server.txt`"

**Comment by Runemoro** [comment]
`latest.log` is enough in this case, I already started fixing it.
