### ISSUE TITLE
Chunkloading error with cubic chunks

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#57]
If you end up in limbo while you have cubic chunks installed, you get stuck at y=700 in limbo, and no chunks will load. This effect persists even if you leave limbo, causing chunks to not load in the overworld. Reloading the world fixes the issue. The console log seems to contain no helpful information.

**Comment by Robijnvogel** [comment]
@Barteks2x would you have any idea why this would be happening?

**Comment by Barteks2x** [comment]
I would probably have to debug it to see what is wrong. My guess is that the mod does dimension transfer in a way cubic chunks doesn't like. Some methods in PlayerChunkMap don't get called or get called twice or in the wrong order or with the wrong arguments. The fact that you can rejoin the world without shutting down mc with task manager means there is no server hang caused by portal search code.

**Comment by Barteks2x** [comment]
This is very likely to be a bug in my code.
