### ISSUE TITLE
[1.12.2] Crashing when returning to overworld from Limbo

### ISSUE THREAD

**Issue by Opulous** [DimensionalDevelopment/DimDoors#69]
I'm using version 3.0.9-287 of dimension doors with Minecraft 1.12.2 and Forge 14.23.3.2702. The mod runs fine up until I try to return to the overworld dimension after being in limbo, at which point the game crashes. 

Here's the crashlog: https://paste.dimdev.org/ajomolusof.txt

Notably, I've never had this happen when traveling into any other dimensions, only with limbo. I'll attach my latest.log file as well, in case that helps. 

[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/2064646/latest.log)

**Comment by Opulous** [comment]
Posting an update here because I've done a bunch of playtesting and narrowed down the source of the crash to an interaction between pretty much any dimension mods and another mod called "VanillaFix": https://minecraft.curseforge.com/projects/vanillafix

VanillaFix seems to claim that their mod optimizes the transition between dimensions, but with enough playtesting I've found it seems to cause problems with this mod as well as other dimension mods like Twilight Forest. This would seem to imply the problem is with VanillaFix and not Dimensional doors, so I'm going to close the issue now.

**Comment by Runemoro** [comment]
@Opulous You should not be crashing. VanillaFix is not causing the crash, but rather just reporting a problem that would otherwise not be seen as a notification on the screen. Are you actually seeing the crash screen, or just a notification at the top of the screen?

The bug that VanillaFix is reporting is either from vanilla, forge or another one of your mods. It is not caused by VanillaFix's dimension change optimization, that's just a simple fix that removes the "Loading Terrain" screen to make you see the other dimension faster but in exchange of incomplete terrain.

**Comment by Opulous** [comment]
The thing is that once I remove VanillaFix, the crash stops happening entirely. I've tried to duplicate the bug without VanillaFix for a few hours, using limbo and many other dimensions that were crashing before, and I've never seen it happen again. That, at the very least, seems to imply it's not Dim Doors' fault at any rate.

**Comment by Runemoro** [comment]
@Opulous Based on the report, the game didn't crash. Did you see a "Minecraft has crashed" screen? If not, then it is not a crash. VanillaFix is just warning you about a problem that was detected from vanilla/forge/another mod, and will only appear in the log file if you remove VanillaFix.
