### ISSUE TITLE
Is there a way to adjust the frequency of door generation?

### ISSUE THREAD

**Issue by scribbler957** [DimensionalDevelopment/DimDoors#77]
It's just that there seem to be an awful lot of doors generating, and I don't see anything in the config that looks like it changes the frequency.
Thank you.

**Comment by ZombieHDGaming** [comment]
If you mean the doors in the world, you have full configurability of how often the doors spawn. For a better idea of what options you're looking for, I'd suggest using the in-game config menu. For most, if not all, of our mods we try to focus more on the menu then the actual config file since we give more info in the menu.

**Comment by scribbler957** [comment]
I'll check the menu then. I think most mods go the other way focusing on the config more than the menu. If I can't find it, I'll reopen. Thanks.
